# docker-compose.yml
version: '3.8'

services:
  fire-detection:
    build: .
    container_name: wildfire-detection
    ports:
      - "8501:8501"
    environment:
      - NASA_API_KEY=your_api_key_here
      - ROBOFLOW_API_KEY=2UgAsIW11EHQmt8gh36L
    volumes:
      - ./cache:/root/.cache  # Для кэширования моделей и данных
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: '2'
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8501/_stcore/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3